### ISSUE TITLE
libcassiemujoco.so: undefined symbol: cassie_sim_foot_positions

### ISSUE THREAD

**Issue by qiaow371** [p-morais/cassie-rl#1]
Hi, Morais, there is an error message here, could you please modify the code or provide reliable dynamic library please?

Thank you very much. :)

**Comment by hyparxis** [comment]
Hey! Sorry about that. I've uploaded a version of the library that should work in the latest commit. You could also try compiling it from here: https://github.com/p-morais/cassie-mujoco-sim. 

Eventually I'll get around to updating the official cassie-mujoco-sim repo too.

**Comment by qiaow371** [comment]
@p-morais Hi, Morais, really appreciate your help because I am doing the undergraduate thesis about cassie :), you are obviously expert, however, when I tried to test the installation, cassie only appear on the screen, she is not actually working, could you tell me what is problem is it? Also, I think you miss something on the cassie folder, so I actually copy some python files from slip_cassie/cassie to make the program in master bench to run.
