### ISSUE TITLE
Reinforcement Learning Alogorithm

### ISSUE THREAD

**Issue by qiaow371** [p-morais/cassie-rl#2]
Hi, Morais, is it possible for you to upload a reinforcement learning sample code for training cassie to walk?

**Comment by hyparxis** [comment]
Hi, if you clone this repo: https://github.com/p-morais/deep-rl and run ```examples/ppo.py``` it's set up to train a Cassie controller that walks forward. You'll need to install pytorch (and optionally, visdom) as well. 

You can load and visualize a trained policy like this (by default models are saved as .pt files in ```trained_models/```):

```python
import torch
import time
from cassie import CassieEnv

env = CassieEnv("walking")

policy = torch.load("path-to-model")
policy.eval() # this turns on input normalization

state = torch.Tensor(env.reset())
while True:
    _, action = policy.act(state)
    state, reward, done, _ = env.step(action.data[0].numpy())

    if done:
        state = env.reset()

    state = torch.Tensor(state)

    env.render()
    time.sleep(1 / 30) # policies run at ~30Hz

``` 

Alternatively, you could train a policy using something like [OpenAI baselines](https://github.com/openai/baselines), but that could take a bit of tweaking to get it to work.

**Comment by qiaow371** [comment]
@p-morais Hi, morais, the model is trained well, thank you:) however, I think for line 6, it should be policy = torch.load("path-to-model") not pytorch, I get a error message which is RuntimeError: The size of tensor a (86) must match the size of tensor b (48) at non-singleton dimension 0, do you know what happened?

Thank you very much!

**Comment by hyparxis** [comment]
Oops, you're right it should be ```torch.load```. And ah, looks like that's because the training code has ```clock_based=True```. Doing ```env = CassieEnv("walking", clock_based=True)``` instead should work :)

**Comment by qiaow371** [comment]
@p-morais Oh, thanks, but a new error message,  from the class, cassieEnv, in step_simulation
    self.u.leftLeg.motorPd.pTarget[i]  = target[i]
TypeError: only size-1 arrays can be converted to Python scalars

**Comment by hyparxis** [comment]
Ah yes, this is because Pytorch adds an extra batch dimension. You can either do action.data[0].numpy() or action.squeeze().numpy() to drop the extra dimension.

**Comment by qiaow371** [comment]
@p-morais Sorry for wasting your time morais, I think it is going to be the last error message
    time.sleep(1 / 30) # policies run at ~30Hz
NameError: name 'time' is not defined

**Comment by hyparxis** [comment]
It's no problem :) It's mostly my bad for not proof-reading the script. That one can be solved with ```import time```.

**Comment by qiaow371** [comment]
Ah, it is working, thank you so much morais :), there are two questions, the first is how many iterations it normally take to achieve stable walking, also, where is the stepdata.bin from, is there any specific algorithm generating this file?

**Comment by hyparxis** [comment]
I think around 500-2000 iterations is normal. And good question! stepdata.bin is created by saving the data generated from running another existing controller in simulation. I'm currently working on alternative ways of generating these "reference motions" that don't require having another functioning controller.

**Comment by qiaow371** [comment]
oh, so you mean the stepdata.bin is generated by the code your provide above? Which files are responsible for stepdata.bin?

**Comment by hyparxis** [comment]
stepdata.bin was generated manually about a year ago, based on a completely different walking controller that was hand designed rather learned through machine learning. There's currently more-or-less 3 categories of controllers for Cassie: learning based (see: https://arxiv.org/abs/1803.05580), optimization based (see: http://www.roboticsproceedings.org/rss14/p54.pdf) and heuristic based (see: https://youtu.be/0e8yNNotA-A?t=169). Stepdata.bin is generated by one of the "heuristic based" controllers.

**Comment by qiaow371** [comment]
Are the heuristic based controller for stepdata.bin or optimized based cassie controller open sourced?

**Comment by qiaow371** [comment]
https://github.com/osudrl/cassie-trajectory-editor, I am not sure have you ever read this code before, from the instruction, it mentioned trajectory editor, I thought it is the heuristic based controller for casse, but I did not see anything in which could generate the trajectory for cassie like the stepdata.bin did.

**Comment by qiaow371** [comment]
Thank you, morais :)
